# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ================ Platform ================

default_platform(:android)

before_all do |lane, options|
  UI.message "Neutral message (usually white)"
  UI.success "Successfully finished processing (usually green)"
  UI.error "Wahaha, what's going on here! (usually red)"
  UI.important "Make sure to use Windows (usually yellow)"
  UI.header "Inputs" # a big box
end

# ================ Lanes ================
platform :android do
  desc "Runs pull-request lane"
  lane :'pull-request' do |options|
    okClean()
    okDependencies()
    okResources()
    okTestAnalyze()
    okTestReport()
    okBuild()
  end

  desc "Runs deploy lane"
  lane :deploy do
    gradle(task: "clean assembleRelease")
  end
end


# ================ Gradle tasks ================

def okClean
    gradle(task: "clean")
end

def okDependencies
    gradle(task: "downloadGradleDependenciesFile")
    gradle(task: "updateGradleDependenciesFile")
    sh("cat ../gradle/libs.versions.toml")
end

def okResources
#    gradle(task: "downloadPoEditorXX")
end

def okTestAnalyze
    gradle(task: "detekt")
    gradle(task: "lint", build_type: "Debug")
    gradle(task: "test", build_type: "Debug")
end

def okTestReport
    gradle(task: "codeCoverageReport")
#     sonar(
#       project_key: "com.poc.android.fastlane",
#       project_version: "1.0",
#       project_name: "android-fastlane",
#       project_language: "kotlin",
#       sonar_login: "sqa_ef79b1106ce43f36ece35764d9459994c08c6f93",
#       sonar_url: "http://localhost:9000/"
#     )
end

def okBuild
    gradle(task: "bundle", build_type: "Debug")
end

def okDeploy
    gradle(
        task: "publish",
        properties: {
            "nexusUser" => ENV['NEXUS_USERNAME'],
            "nexusPass" => ENV['NEXUS_PASSWORD'],
            "nexusVersion" => ENV['VERSION'],
            "versionName" => ENV['VERSION'],
        }
    )
    appcenter_upload(
      api_token: ENV['ODS_DEV_TEST_HOCKEY_API_KEY'],
      owner_name: "Dev-Test-ODS",
      owner_type: "organization", # Default is user - set to organization for appcenter organizations
      app_name: "mb-hb-android-feature-landing-openbankAr-stg",
      file: ENV['BITRISE_MAPPING_PATH'],
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
end