# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ================ Platform ================

default_platform(:android)

# before_all do |lane, options|
#   sh("brew install sonar-scanner")
# end

# ================ Lanes ================
platform :android do
  desc "Runs pull-request lane"
  lane :'pull-request' do |options|
    okClean()
    okTestAnalyze()
    okTestReport()
    okBuild()
  end

  desc "Runs deploy lane"
  lane :deploy do
    gradle(task: "clean assembleRelease")
  end
end


# ================ Gradle tasks ================

def okClean
    gradle(task: "clean")
end

def okTestAnalyze
    gradle(task: "detekt")
    gradle(task: "lint", build_type: "Debug")
    gradle(task: "test", build_type: "Debug")
end

def okTestReport
    gradle(task: "codeCoverageReport")
#     sonar(
#       project_key: "com.poc.android.fastlane",
#       project_version: "1.0",
#       project_name: "android-fastlane",
#       project_language: "kotlin",
#       sonar_login: "sqa_ef79b1106ce43f36ece35764d9459994c08c6f93",
#       sonar_url: "http://localhost:9000/"
#     )
end

def okBuild(options)
    gradle(task: "bundle", build_type: "Debug")
end